baseURL = 'https://yeralex.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'typo'

[params]
# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am an Italian Software Engineer with a strong foundation in computer science and a passion for solving complex problems.
I am interested in a range of topics, including algorithms, distributed systems, databases, and information retrieval.
"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'


theme = 'auto | light | dark'


colorPalette = 'default'

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

