baseURL = 'https://www.yeralex.com/'
languageCode = 'en-us'
title = "XINYI YANG"
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-DRSLEBGB06"


[params]
# Intro on main page, content is markdown
homeIntroTitle = 'About'
homeIntroContent = """
I am Xinyi Yang from Mainland China, the owner of a small international trading company. I have a Bachelor's Degree in Physics from Nanjing University. Inspired by some ideas of **The Almanack Of Naval Ravikant**, I have restarted my blog to record some of my thoughts and experiences. 
"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'

paginationSize = 100

theme = 'light'

breadcrumbs = false

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "gallery"
url = "/gallery"
